name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: npm install

      - name: Configure environment variables
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  apiUrl: '${{ secrets.API_URL }}'," >> src/environments/environment.prod.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'," >> src/environments/environment.prod.ts
          echo "  apiEndpoint: '${{ secrets.API_ENDPOINT }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Build Angular app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --depth 1 --branch gh-pages https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r dist/currency/browser/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
